version: '3.5'
services:
  micro-service-updater:
    restart: always
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $SSL_CERT_FILE:/ssl/server.crt
      - $SSL_KEY_FILE:/ssl/server.key
      - ./services/:/services
    ports:
      - "$SERVICE_PORT:9000"
